/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_14 (
    input z,
    input n,
    input v,
    input [5:0] alufn,
    output reg [15:0] cmp
  );
  
  
  
  always @* begin
    cmp[1+14-:15] = 15'h0000;
    
    case (alufn)
      6'h33: begin
        cmp[0+0-:1] = z;
      end
      6'h35: begin
        cmp[0+0-:1] = n ^ v;
      end
      6'h37: begin
        cmp[0+0-:1] = z | (n ^ v);
      end
      default: begin
        cmp[0+0-:1] = 1'h0;
      end
    endcase
  end
endmodule
