/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module led_matrix_driver_7 (
    input clk,
    input rst,
    input [1:0] sign,
    output reg [7:0] row,
    output reg [7:0] col
  );
  
  
  
  wire [8-1:0] M_led_display_seg;
  wire [8-1:0] M_led_display_sel;
  reg [32-1:0] M_led_display_values;
  multi_led_display_14 led_display (
    .clk(clk),
    .rst(rst),
    .values(M_led_display_values),
    .seg(M_led_display_seg),
    .sel(M_led_display_sel)
  );
  
  always @* begin
    M_led_display_values = 32'h88888888;
    
    case (sign)
      1'h0: begin
        M_led_display_values = 32'h45677654;
      end
      1'h1: begin
        M_led_display_values = 32'h01233210;
      end
      2'h2: begin
        M_led_display_values = 32'h88988988;
      end
      2'h3: begin
        M_led_display_values = 32'h88888888;
      end
    endcase
    col = M_led_display_seg;
    row = ~M_led_display_sel[0+7-:8];
  end
endmodule
