/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module matrix_lut_18 (
    input [3:0] value,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (value)
      1'h0: begin
        segs = 8'h80;
      end
      1'h1: begin
        segs = 8'h40;
      end
      2'h2: begin
        segs = 8'h20;
      end
      2'h3: begin
        segs = 8'h10;
      end
      3'h4: begin
        segs = 8'h01;
      end
      3'h5: begin
        segs = 8'h02;
      end
      3'h6: begin
        segs = 8'h04;
      end
      3'h7: begin
        segs = 8'h08;
      end
      4'h8: begin
        segs = 8'h00;
      end
      4'h9: begin
        segs = 8'hff;
      end
      default: begin
        segs = 8'h00;
      end
    endcase
  end
endmodule
